/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 21 03:07:32 GMT 2015
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class BankAccount_ESTest extends BankAccount_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 25 covered goals:
   * Goal 1. Weak Mutation 4: BankAccount.debit(D)D:11 - ReplaceComparisonOperator >= -> ==
   * Goal 2. BankAccount.debit(D)D:negative
   * Goal 3. BankAccount.<init>(D)V: Line 7
   * Goal 4. BankAccount.<init>(D)V: Line 8
   * Goal 5. BankAccount.debit(D)D: Line 11
   * Goal 6. BankAccount.debit(D)D: Line 15
   * Goal 7. BankAccount.debit(D)D: Line 16
   * Goal 8. BankAccount.<init>(D)V: root-Branch
   * Goal 9. BankAccount.debit(D)D: I6 Branch 1 IFGE L11 - true
   * Goal 10. Weak Mutation 0: BankAccount.<init>(D)V:7 - InsertUnaryOp Negation
   * Goal 11. Weak Mutation 1: BankAccount.debit(D)D:11 - InsertUnaryOp Negation
   * Goal 12. Weak Mutation 2: BankAccount.debit(D)D:11 - InsertUnaryOp Negation
   * Goal 13. Weak Mutation 7: BankAccount.debit(D)D:15 - InsertUnaryOp Negation
   * Goal 14. Weak Mutation 8: BankAccount.debit(D)D:15 - InsertUnaryOp Negation
   * Goal 15. Weak Mutation 9: BankAccount.debit(D)D:15 - ReplaceArithmeticOperator - -> +
   * Goal 16. Weak Mutation 10: BankAccount.debit(D)D:15 - ReplaceArithmeticOperator - -> %
   * Goal 17. Weak Mutation 11: BankAccount.debit(D)D:15 - ReplaceArithmeticOperator - -> *
   * Goal 18. Weak Mutation 12: BankAccount.debit(D)D:15 - ReplaceArithmeticOperator - -> /
   * Goal 19. Weak Mutation 13: BankAccount.debit(D)D:16 - InsertUnaryOp Negation
   * Goal 20. BankAccount.<init>(D)V
   * Goal 21. BankAccount.debit(D)D
   * Goal 22. BankAccount.<init>(D)V
   * Goal 23. BankAccount.debit(D)D
   * Goal 24. Branch BankAccount.debit(D)D: I6 Branch 1 IFGE L11 - true in context: BankAccount:debit(D)D
   * Goal 25. Branch BankAccount.<init>(D)V: root-Branch in context: BankAccount:<init>(D)V
   */

  @Test
  public void test0()  throws Throwable  {
      BankAccount bankAccount0 = new BankAccount(1529.3760546);
      double double0 = bankAccount0.debit((-2032.249765187));
      assertEquals((-2032.249765187), double0, 0.01D);
  }

  //Test case number: 1
  /*
   * 9 covered goals:
   * Goal 1. BankAccount.debit(D)D: Line 12
   * Goal 2. BankAccount.debit(D)D: I6 Branch 1 IFGE L11 - false
   * Goal 3. Weak Mutation 3: BankAccount.debit(D)D:11 - ReplaceComparisonOperator >= -> -1
   * Goal 4. Weak Mutation 6: BankAccount.debit(D)D:12 - InsertUnaryOp Negation
   * Goal 5. Weak Mutation 10: BankAccount.debit(D)D:15 - ReplaceArithmeticOperator - -> %
   * Goal 6. BankAccount.debit(D)D:zero
   * Goal 7. Branch BankAccount.debit(D)D: I6 Branch 1 IFGE L11 - false in context: BankAccount:debit(D)D
   * Goal 8. Weak Mutation 5: BankAccount.debit(D)D:11 - ReplaceComparisonOperator >= -> >
   * Goal 9. BankAccount.debit(D)D:positive
   */

  @Test
  public void test1()  throws Throwable  {
      BankAccount bankAccount0 = new BankAccount(1529.3760546);
      double double0 = bankAccount0.debit(1529.3760546);
      assertEquals(1529.3760546, double0, 0.01D);
      
      double double1 = bankAccount0.debit(1529.3760546);
      assertEquals(0.0, double1, 0.01D);
  }
}
